### ISSUE TITLE
Not able to startup.

### ISSUE THREAD

**Issue by WallE256** [UESTC-ACM/CDOJ#286]
When I thought it was going to work, it didn't... http://pastebin.com/JufvEtcf What should I do?

**Comment by lyhypacm** [comment]
Hi, we use jettyRun instead of jettyEclipseRun now. please have a try.

The document is out of date.

**Comment by WallE256** [comment]
It works.. But looks like this: http://i.imgur.com/7Y92MIv.png ... None of the buttons are clickable. Do I need to acces it localy, or i did something wrong?

**Comment by lyhypacm** [comment]
I seems that the UI is not compiled correctly. 

Please try run `npm install` then `grunt build` in `trunk/static` folder.

**Comment by WallE256** [comment]
http://pastebin.com/gUmmg6Uj

**Comment by lyhypacm** [comment]
`sudo npm install grunt-cli -g`
then try grunt again

**Comment by WallE256** [comment]
Now it worked. But looks the same. I just checked the database, and it was OK.

**Comment by withlqs** [comment]
```
sudo npm install grunt-cli -g
```

and

using bower by root account will occur error;
please edit  */trunk/static/package.json*

```
postinstall": "./node_modules/.bin/bower install"
```

```
postinstall": "./node_modules/.bin/bower install --allow-root"
```

**Comment by WallE256** [comment]
Now works. Thanks man.. But, what is the default login?? :smile:

**Comment by withlqs** [comment]
you can try in staticV2

run
```
npm install && bower install --allow-root && grunt build
```

hahaha

**Comment by withlqs** [comment]
not root

==.

**Comment by WallE256** [comment]
I figured that one out. But, can you add more test cases, and if yes, how?

**Comment by withlqs** [comment]
oh... I can not understand your meaning... add test case for a problem in OJ?

**Comment by WallE256** [comment]
Yes, when adding a problem, can you put more test cases?

**Comment by lyhypacm** [comment]
Sorry for late reply.

When you editing a problem, you can upload a `data.zip` file with input/output data inside. There can be more than one test cases in the zip package, and the input files(with extension `*.in`) and output files(with extension `*.out`) are matched according to their names. The input / output files will be sorted in server side **lexicographically**.

**Comment by WallE256** [comment]
Thanks, that was all I needed. Closed.
