### ISSUE TITLE
Strange RF on Archlinux_x64

### ISSUE THREAD

**Issue by razrLeLe** [UESTC-ACM/CDOJ#292]
I judged the simple code below on my Archlinux_x64 machine, but it returned RF while it is supposed to be AC.

<pre>#include <iostream>
using namespace std;

int main(){
    int a;
    for(int i = 0; i < 100000; i++)
    {
        cin >> a;
        cout << a << endl;
    }
    return 0;
}</pre>

here is the log:

<pre>TRACE [2015-12-24 18:36:51] [include/judge_func.h:259] [uid:1] malarm: 17000
WARNING [2015-12-24 18:36:51] [src/main.cc:56] [uid:1] [compiler] cwd = /home/razrlele/lab/RAZROJ/judger/bin
TRACE [2015-12-24 18:36:51] [include/judge_func.h:367] [uid:1] [compiler] set compile limit ok
TRACE [2015-12-24 18:36:51] [src/main.cc:79] [uid:1] [compiler] start: g++ -static -m32 -w -O2 -DONLINE_JUDGE -o ./test/a.out ./test/test.cc
TRACE [2015-12-24 18:36:51] [src/main.cc:115] [uid:1] compiler finished
TRACE [2015-12-24 18:36:51] [src/main.cc:118] [uid:1] compile succeeded
DEBUG [2015-12-24 18:36:51] [src/main.cc:159] [uid:1] input_file        ./test/input.in
DEBUG [2015-12-24 18:36:51] [src/main.cc:160] [uid:1] output_file_std   ./test/data.out
TRACE [2015-12-24 18:36:51] [src/main.cc:215] [uid:1] start judging...
TRACE [2015-12-24 18:36:51] [include/judge_func.h:277] [uid:1] [executive] io redirect ok!
DEBUG [2015-12-24 18:36:51] [include/judge_func.h:392] [uid:1] [executive] cwd: /home/razrlele/lab/RAZROJ/judger/bin/test
TRACE [2015-12-24 10:36:51] [include/judge_func.h:411] [uid:1] [executive] set_security_option ok
TRACE [2015-12-24 10:36:51] [include/judge_func.h:321] [uid:1] [executive] set limit ok
DEBUG [2015-12-24 10:36:51] [src/main.cc:181] [uid:1] [executive] tl: 2000, tu: 0, tla: 314
TRACE [2015-12-24 10:36:51] [include/judge_func.h:259] [uid:1] [executive] malarm: 2314
TRACE [2015-12-24 10:36:51] [src/main.cc:191] [uid:1] [executive] begin executive: ./test/a.out
TRACE [2015-12-24 10:36:51] [include/log_func.h:119] [uid:1] [executive] log_close
TRACE [2015-12-24 18:36:53] [src/main.cc:335] [uid:1] restricted function, syscall_id: 140
TRACE [2015-12-24 18:36:53] [src/main.cc:356] [uid:1] not ac/pe, no need to continue
TRACE [2015-12-24 18:36:53] [include/judge_func.h:614] [uid:1] result: 13, 356KB, 1019ms
TRACE [2015-12-24 18:36:53] [include/log_func.h:119] [uid:1] log_close
</pre>

I am so confused why there is a 140 system call. And more confusingly, same codes and same commands run properly on Ubuntu_x64.

Could you please provide me with some ideas about how to figure it out?

Thanks so much.

**Comment by razrLeLe** [comment]
Problem solved.

When it is in Archlinux_X64, the owner of the stdout_executive.txt is root, but when it is in Ubuntu_X64, it is owned by normal user, I think this causes the system call sys_getpriority(%rax is 140 in X86_64 Linux). 

I have no idea how to correct output file's priority, but I can solve this problem by editing rf_table.h.

**Comment by lyhypacm** [comment]
Just an idea, can we keep all files generated with same owner?

**Comment by ruinshe** [comment]
Close this because we switched to new judge core.
