### ISSUE TITLE
Url Needs to Be Updated.

### ISSUE THREAD

**Issue by inouetoukyou** [UESTC-ACM/CDOJ#298]
![qq 20170909002619](https://user-images.githubusercontent.com/15509988/30221415-bf73d614-94f5-11e7-8e89-88d60911537d.png)
http://en.gravatar.com/ may not be perfect, because I sometimes can't open it. https://en.gravatar.com/ would be better.

**Comment by ruinshe** [comment]
Fixed at 0d52a558b20a6d5d67dfb60aae6b543b1182e92f.
