### ISSUE TITLE
System Error如何解决

### ISSUE THREAD

**Issue by nedchu** [UESTC-ACM/CDOJ#304]
使用Vjudge提交之后获得了System Error，请问可能是什么原因导致相关的问题
![image](https://user-images.githubusercontent.com/11944144/41447621-a568c864-7088-11e8-9309-21e22ae2fc1b.png)

**Comment by LaPluses** [comment]
CDOJ的服务器现在在云上，原本题目的数据没有传上去，所以造成System Error.
后续修复消息请关注新人群.
